name: test-migrations
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.NEON_TOKEN }}
      PG_CREDENTIALS: ${{ secrets.NEON_PG_CREDENTIALS }}
      PG_CLUSTER: ${{ secrets.NEON_CLUSTER }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: check migration on branch
        run: |
          # create branch, and set BRANCH_NAME env variable
          echo 'BRANCH_NAME<<EOF' >> $GITHUB_ENV
          curl -o - -X POST -H "Authorization: Bearer $API_TOKEN" https://console.stage.neon.tech/api/v1/projects/$PG_CLUSTER/branches | jq -r '.name' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          # apply migrations on branch
          echo "DATABASE_URL=postgres://$PG_CREDENTIALS@$BRANCH_NAME.cloud.stage.zenith.tech/main" >> $GITHUB_ENV
          npx prisma generate && npx prisma migrate deploy

      - name: apply migration on main
        run: |
          echo "DATABASE_URL=postgres://$PG_CREDENTIALS@$PG_CLUSTER.cloud.stage.zenith.tech/main" >> $GITHUB_ENV
          npx prisma generate && npx prisma migrate deploy

      - name: deploy on Vercel
        run: |
          npx vercel --token ${VERCEL_TOKEN}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
