name: test-migrations
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_TOKEN: ${{ secrets.NEON_TOKEN }}
      PG_CREDENTIALS: ${{ secrets.NEON_PG_CREDENTIALS }}
      PG_CLUSTER: ${{ secrets.NEON_CLUSTER }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: create branch
        run: |
          # create branch, and set BRANCH_NAME env variable
          echo 'BRANCH_NAME<<EOF' >> $GITHUB_ENV
          curl -o - -X POST -H "Authorization: Bearer $API_TOKEN" https://console.stage.neon.tech/api/v1/projects/$PG_CLUSTER/branches | jq -r '.id' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: switch to branch
        run: |
          echo "BRANCH_URL=postgres://$PG_CREDENTIALS@${{ env.BRANCH_NAME }}.cloud.stage.neon.tech/main" >> $GITHUB_ENV

      - name: apply migration on branch
        run: |
          npx prisma generate && npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ env.BRANCH_URL }}

      - name: deploy on Vercel
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
